ALTER TABLE EXACT.PO_ACQ_CONTRACT_FREQ DROP CONSTRAINT P_KEY_1; -
ALTER TABLE EXACT.PO_ACQ_CONTRACT_FREQ ADD COLUMN AUTO_ID INTEGER NOT NULL WITH DEFAULT 0;
CREATE SEQUENCE PO_ACQ_CONTRACT_FREQ_SEQUENCE START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE TRIGGER PO_ACQ_CONTRACT_FREQ_TRIGGER NO CASCADE BEFORE INSERT ON EXACT.PO_ACQ_CONTRACT_FREQ
REFERENCING NEW AS NEW FOR EACH ROW MODE DB2SQL BEGIN ATOMIC SET (NEW.AUTO_ID) = (NEXTVAL FOR PO_ACQ_CONTRACT_FREQ_SEQUENCE); END
Call Sysproc.admin_cmd ('reorg Table EXACT.PO_ACQ_CONTRACT_FREQ')
UPDATE EXACT.PO_ACQ_CONTRACT_FREQ SET AUTO_ID = PO_ACQ_CONTRACT_FREQ_SEQUENCE.NEXTVAL
ALTER TABLE EXACT.PO_ACQ_CONTRACT_FREQ ADD CONSTRAINT P_KEY_1 PRIMARY KEY (AUTO_ID)